# Run Model
Dit notebook kan gebruikt worden om BrfRFE_model1 te draaien. Dit model is bedoeld om te voorspellen of een kandidaat starter zal worden op basis van de data die verzamelt is voordat het eerste telefonisch contact is geweest.

In [29]:
# !git clone https://github.com/peterfaasse/BastianLewisModelRepo.git

## Import necessary libraries

In [3]:
import pandas as pd
import numpy as np
import os
import json
from datetime import datetime
import re
from helper import get_most_recent_file, make_dir
from data_prep import run_data_prep, prepare_input_dataframe, prep_dataset_for_modelling, replace_invalid_values

## Upload data
Je kan de data van de kandidaten waarover je wilt voorspellen of ze starter worden uploaden in de map "kandidaat_data". Dit dient in de vorm van een excel te zijn met de naam "kandidaten_[DATUM].xlsx". Op de plek van [DATUM] vul je de datum in van uploaden in het format yyyymmdd, zonder streepjes of iets er tussen. Bijvoorbeeld een data bestand geupload op 11 augustus 2024 heeft de naam "kandidaten_20240811.xlsx". 

De excel heeft een aantal vaste kolommen en kolomnamen. Een voorbeeld excel bevind zich in kandidaten_data/voorbeeld_kandidaten.xlsx. Let op dat wijzigingen in de namen van kolommen of antwoordcategorieen impact hebben op de bruikbaarheid van de data en de kwaliteit van het model.

## Set directories and load data

In [26]:
kandidaten_dir = r"C:\Users\peter\Projects\HR_Forecasting\kandidaat_data"
data_dir = r"C:\Users\peter\Projects\HR_Forecasting\data"
model_dir = r"C:\Users\peter\Projects\HR_Forecasting\models"
supporting_data_dir = r"C:\Users\peter\Projects\HR_Forecasting\supporting_data"
file_path = get_most_recent_file(kandidaten_dir)
df_kandidaten = pd.read_excel(file_path)

In [27]:
df_kandidaten = pd.read_excel(r"C:\Users\peter\Projects\HR_Forecasting\data\BastianLewisData.xlsx", "Result 1")

In [28]:
##df_kandidaten = df_kandidaten.sample(100)

## Lees model en metadata in

In [29]:
## select model
model_name = "model_3" # or select "model_2"

## set paths
model_path = os.path.join(model_dir, model_name + ".pkl")
meta_path = os.path.join(model_dir, model_name+"_meta.json")

In [30]:
#laad model en metadata
brf_rfe = pd.read_pickle(model_path)
with open(meta_path, 'r') as file:
    model_meta = json.load(file)

## Prepareer data voor forecasting

In [31]:
#laad dataset metadata in voor dit model
json_path = os.path.join(model_dir,f"{model_meta['dataset'].split('_final')[0]}_categorical_meta_data.json")
with open(json_path, "r") as file:
    categorical_meta_data = json.load(file)

In [32]:
#prep dataframe, select only model variables fil missings
df_model_input = run_data_prep(df_kandidaten, supporting_data_dir)
ids = df_model_input['id']
df_model_input = replace_invalid_values(df_model_input, categorical_meta_data)
df_model_input = prepare_input_dataframe(df_model_input, model_meta['selected_features'])
df_model_input.fillna(999, inplace=True)

c:\Users\peter\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

removed 5804 candidates who did not have prioriteit 1
removed 10 candidates who did not have NULL for afwijsBasisGegevens

## Make predictions and save in Results

In [33]:
predictions = brf_rfe.predict(df_model_input)
probas = brf_rfe.predict_proba(df_model_input)
model_pred = pd.DataFrame()
model_pred['id'] = ids
model_pred['pred'] = list(predictions)
model_pred['prob'] = probas[:,1]

datetimestring = re.sub(r'\D', '', str(datetime.today()))
make_dir("results")
output_path = f"results/{model_name}_predictions_{datetimestring}.xlsx"
model_pred.to_excel(output_path, index=False)

c:\Users\peter\anaconda3\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but BalancedRandomForestClassifier was fitted without feature names
  warnings.warn(
c:\Users\peter\anaconda3\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but BalancedRandomForestClassifier was fitted without feature names
  warnings.warn(

Directory already exists.

In [34]:
df_kandidaten

,id,cdate,firstName,lastName,afwijsRedenContact,uitkomstIntake,recruitercode,datumIntake,prioriteit,belafspraak,...,Salarisindicatie,datum en tijd gesprek,Verloning marge stopper of W&S overname,Overname bedrag (W&S),groupid,stage,status,contractgesprek,starter,berekening
0,27149,2024-05-29 14:53:57,NaN,NaN,NaN,NaN,9.0,NaN,1.0,2024-05-31T10:15:00+02:00,...,NaN,NaN,NaN,NaN,1,5,0,NaN,0,NaN
1,27138,2024-05-29 10:25:32,NaN,NaN,NaN,NaN,9.0,NaN,1.0,2024-05-30T09:50:00+02:00,...,NaN,NaN,NaN,NaN,1,5,0,NaN,0,NaN
2,27135,2024-05-29 09:31:01,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,1,5,2,NaN,0,NaN
3,27132,2024-05-29 08:15:03,NaN,NaN,NaN,NaN,9.0,NaN,1.0,2024-05-30T09:40:00+02:00,...,NaN,NaN,NaN,NaN,1,5,0,NaN,0,NaN
4,27129,2024-05-29 00:37:19,NaN,NaN,NaN,NaN,9.0,NaN,1.0,2024-05-30T10:40:00+02:00,...,NaN,NaN,NaN,NaN,1,5,0,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9938,22502,2023-11-16 15:12:03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,10,140,0,NaN,0,NaN
9939,22629,2023-11-20 15:56:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,10,126,0,NaN,0,NaN
9940,22721,2023-11-22 18:59:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,10,124,0,NaN,0,NaN
9941,8854,2022-06-22 13:46:33,NaN,NaN,Geen_reactie,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,1,25,2,NaN,0,NaN
9942,19004,2023-06-29 20:50:25,NaN,NaN,Geen_reactie,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,2,2,NaN,0,NaN

In [36]:
df_model_input == df_final_bastianlewis_selected

,cdate,recruitercode,belafspraak,leeftijd,geboortedatum,Verloning marge stopper of W&S overname,jaar_ervaring,diff_days,Voorkeursbranche_elektrotechniek,Voorkeursbranche_installatietechniek
0,True,True,True,True,True,False,True,True,True,True
1,True,True,True,True,True,False,True,True,True,True
2,True,False,True,True,True,False,True,False,True,True
3,True,True,True,True,True,False,False,True,True,True
4,True,True,True,True,True,False,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...
4124,True,True,True,False,True,False,False,True,True,True
4125,True,True,True,False,True,False,False,True,True,True
4126,True,True,True,False,True,False,False,True,False,True
4127,True,True,True,False,True,False,False,True,True,True
4128,True,True,True,True,True,False,False,True,False,True

In [22]:
df_model_input.reset_index() == df_final_bastianlewis_selected.reset_index()

ValueError: Can only compare identically-labeled DataFrame objects

In [14]:
df_final_bastianlewis = pd.read_csv(r"C:\Users\peter\Projects\HR_Forecasting\data\BastianLewisData_final.csv")

In [20]:
df_final_bastianlewis_selected = df_final_bastianlewis[model_meta['selected_features']]
df_final_bastianlewis_selected.head()

,cdate,recruitercode,belafspraak,leeftijd,geboortedatum,Verloning marge stopper of W&S overname,jaar_ervaring,diff_days,Voorkeursbranche_elektrotechniek,Voorkeursbranche_installatietechniek
0,1716994437000000000,9.0,1717143300000000000,24.0,965433600000000000,NaN,2.000000,1.0,0,0
1,1716978332000000000,9.0,1717055400000000000,42.0,364348800000000000,NaN,7.000000,0.0,0,0
2,1716975061000000000,NaN,-9223372036854775808,32.0,696038400000000000,NaN,2.500000,NaN,0,0
3,1716970503000000000,9.0,1717054800000000000,18.0,1115424000000000000,NaN,0.166667,0.0,0,0
4,1716943039000000000,9.0,1717058400000000000,23.0,961372800000000000,NaN,0.500000,1.0,0,0

## Todos
1. Fix nieuwe kolomwaardes naar other
2. Vergelijk model oude data met model nieuwe data
3. Voeg schone textdata toe aan data en draai modellen opnieuw
4. Voeg map toe met model evaluatie metrics en trees
5. Creeer aparte environment